### ISSUE TITLE
resume() does not work if called immediately in onDuration callback

### ISSUE THREAD

**Issue by volgin** [google/flutter.plugins#106]
The following code works as expected, except no music is playing :(

```
audio = Audio.loadFromByteData(...);

.. wait for onDuration call ...

await audio!.resume();
```

Adding a small delay (I added 100 milliseconds) before resume() solves the issue. I suspect that it is because the bytes are not fully loaded if the call is made immediately. It does seem strange, though, because I wait for the onDuration call before calling resume().

It would be nice to document the correct behavior somewhere - it would have saved me countless hours trying to figure out why the music is not playing when all code executes as expected.

**Comment by monkeyswarm** [comment]
Device and operating  system  version?

**Comment by volgin** [comment]
iOs, any device. It happens more often/predictably on a physical device, but I've seen it on a simulator too.

**Comment by volgin** [comment]
I have to mention that I have not tried it on an Android device.

**Comment by monkeyswarm** [comment]
The onDuration callback doesn't mean that the content is ready for playback, it just means that the duration of the audio is known. But don't have to wait for the onDuration callback in order to request playback.

What happens when you just do

final audio = Audio.loadFromByteData(...)...resume();

?

If it's still an issue, then I would look at debugging the iOS code, because the native iOS code is 
1 setting up an AVAudioPlayer with byte data, then 
2 calling [prepareToPlay], and then 
3 you are immediately calling [play]. 

It's possible that calling [AVAudioPlayer prepareToPlay] and then [AVAudioPlayer play] in immediate sequence is a problem.

How long is your byte data?
