### ISSUE TITLE
localfile is not support

### ISSUE THREAD

**Issue by wanjm** [google/flutter.plugins#33]
current only support asset but other local file is not support

**Comment by monkeyswarm** [comment]
Could you elaborate on your use case? Do you mean 
a) local files that are part of the apps android/ios package, or do you mean 
b) reading files from common storage (i.e. sdcard on Android)?

For a), I don't see why shared assets need to be packaged in the native package instead of as an asset in the flutter project. 
For b), I can see why loading from a path is easier, and I'll look into it. However, in the meantime, you should be able to get a path to the file and read it as ByteData, then load it that way.

**Comment by csacchetti** [comment]
I would also ask that this function be implemented which makes plug-in more functional and complete.

**Comment by monkeyswarm** [comment]
Added in version 1.2.0

**Comment by volgin** [comment]
It still does not work on Android because of file permissions. A workaround is to load ByteData and use it to play a local file.
