### ISSUE TITLE
Error with Android when I RUN in RELEASE MODE

### ISSUE THREAD

**Issue by csacchetti** [google/flutter.plugins#43]
When I try to run in release mode my app (but the same error is show in Example too) I have in Run console this error
<img width="1149" alt="Schermata 2020-01-04 alle 11 40 36" src="https://user-images.githubusercontent.com/46923349/71764664-f83a0b80-2eea-11ea-88c3-a04c4e2bb358.png">
I have do the change in Manifest like suggest. But also here there's a message error
<img width="1050" alt="Schermata 2020-01-04 alle 11 56 02" src="https://user-images.githubusercontent.com/46923349/71764670-1ef84200-2eeb-11ea-9537-60ea8a865b6d.png">
The app is also installed but it has the same problem as before: The audio interrupts after a few minutes.

**Comment by monkeyswarm** [comment]
There's several different issues here. 

Focusing on the audio interrupt. I'm not concerned about the screenshots above; I get the same behavior on my setup. 

1) What is your OS version and type of phone?
2) When you start audio playback, does a notification show up? (And stay visible?)
3) Does running in debug mode behave differently than running in release mode?

**Comment by csacchetti** [comment]
Huawei P20 lite
Model ANE-LX1
EMUI 9.1.0

No notification

**Comment by monkeyswarm** [comment]
You should see a notification like the below.

- Are you playing the audio on the fourth card ("Example 4: background playback with...")? That's the only button in the example app with background audio.

- Are you using the most recent version of the example app (as part of the plugin version 1.1.1?)

- Otherwise then perhaps your system is blocking unknown Android Services. Is there anything in your security or battery settings that does this? 

I have access to a Huawei phone on Monday, I'll try it on that then.

![image](https://user-images.githubusercontent.com/1235083/71772198-ead94d00-2efb-11ea-8e72-28dd9295b51b.png)
