### ISSUE TITLE
Playlist from list of Urls

### ISSUE THREAD

**Issue by wisecoders** [google/flutter.plugins#52]
Thanks for the plugin. Could you please let me know how to implement playlist capability.

**Comment by monkeyswarm** [comment]
Please take general programming questions to public Q&A forums like Stack Overflow.

**Comment by wisecoders** [comment]
I dont think this general programming question and it is specific to the plugin you have developed.

I tried various way to implement but it is breaking one way or another. (same audio plays repeatedly and notification seekbar is not reset properly). as you are owner I thought you would be able to point to the right direction.

**Comment by wisecoders** [comment]
question is not about programming rather than it is about audiofileplayer plugin. I tried to implement various ways to achieve this but not working (same audio is playing and notification bar seek bar is not being reset). 

I thought as a owner, you should be able to help me.

**Comment by monkeyswarm** [comment]
If you have a specific question as to plugin functionality (such as with the elements you mention: notification display and seek bar), then please ask that. Or if you have an example of things not working as described in the API, then please detail that with a) steps to reproduce (including code samples if applicable), b) expected behavior, c) actual behavior.

**Comment by wisecoders** [comment]
Thanks for the quick response. I will create a another ticket..
